/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sonaypet.vista;
import com.sonaypet.modelo.dao.ClienteVeterinariaDAO;
import com.sonaypet.modelo.dao.MascotaDAO;
import com.sonaypet.modelo.entidades.ClienteVeterinaria;
import com.sonaypet.modelo.entidades.Mascota;
import static com.sonaypet.vista.frmPrincipal.DesktopPane;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author cesar
 */
public class ListarClientesCita extends javax.swing.JInternalFrame {
    ArrayList<String>nombreM = new ArrayList();
    ClienteVeterinariaDAO dao = new ClienteVeterinariaDAO();
    ClienteVeterinaria cliente = new ClienteVeterinaria();
    DefaultTableModel modelo = new DefaultTableModel();
    MascotaDAO daoM = new MascotaDAO();
    Mascota mascota = new Mascota();
    int id;
    
    ArrayList<Integer>idsM = new ArrayList();

    /**
     * Creates new form ListarClientes
     */
    public ListarClientesCita() {
        initComponents();
        listar();
       
    }
    public void buscarMascota(){
        cbxMascota.removeAllItems();
        cbxMascota.addItem("SELECCIONAR");
        List<Mascota> lista = daoM.buscarTodosID(id);
        for(int i = 0; i < lista.size(); i++){
           
            nombreM.add(lista.get(i).getNombre());
            cbxMascota.addItem(nombreM.get(i));
            idsM.add(lista.get(i).getId());
        }
        
        
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
        public void cargarFormulario (JPanel panel, String titulo){
       JInternalFrame frm = new JInternalFrame(titulo);
       frm.setContentPane (panel);
       frm.setSize(600,600);
       DesktopPane.add(frm);
       frm.setVisible(true);
       frm.setMaximizable(true);
       frm.setClosable(true);
       frm.setIconifiable(true);
   }
        
        public void listar(){
        List<ClienteVeterinaria> lista = dao.listar();
        modelo = (DefaultTableModel)tbl3.getModel();
        Object[]ob = new Object[9];
        for(int i = 0; i < lista.size(); i++){
            ob[0] = lista.get(i).getId();
            ob[1] = lista.get(i).getNombre();
            ob[2] = lista.get(i).getApellido();
            ob[3] = lista.get(i).getFechaNac();
            ob[4] = lista.get(i).getDireccion();
            ob[5] = lista.get(i).getTelefono();
            ob[6] = lista.get(i).getGenero();
            ob[7] = lista.get(i).getEmail();
            ob[8] = lista.get(i).getPass();
            modelo.addRow(ob);
              
        }
        
        tbl3.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cbxMascota = new javax.swing.JComboBox<>();

        tbl3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO", "FECHA DE NACIMIENTO", "DIRECCION", "TELEFONO", "SEXO", "EMAIL", "CONTRASEÑA"
            }
        ));
        tbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl3);

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbxMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        cbxMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cbxMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl3MouseClicked
        int fila = tbl3.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");

        }else{
            id = Integer.parseInt(tbl3.getValueAt(fila, 0).toString());
            buscarMascota();
            

        }
    }//GEN-LAST:event_tbl3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     
        if(cbxMascota.getItemCount() == 1){  
        JOptionPane.showMessageDialog(this, "Debe seleccionar una mascota para agendar cita");
        }
        else{
        AgendarCitas mascotas = new AgendarCitas(id, idsM.get(cbxMascota.getSelectedIndex()-1));
    
        cargarFormulario ((JPanel)mascotas.getContentPane(), "..:: Agendar Cita ::..");
        
        this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxMascota;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl3;
    // End of variables declaration//GEN-END:variables
}
